ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "trialStartedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "trialEndsAt" TIMESTAMP(3);

UPDATE "User"
SET "trialEndsAt" = COALESCE("trialEndsAt", "createdAt" + INTERVAL '3 days');

ALTER TABLE "Subscription" ADD COLUMN IF NOT EXISTS "amountMinor" INTEGER;
ALTER TABLE "Subscription" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';

CREATE INDEX IF NOT EXISTS "User_country_idx" ON "User"("country");
